CREATE TABLE product (
  id SERIAL PRIMARY KEY,
  name VARCHAR NULL DEFAULT NULL,
  slogan VARCHAR NULL DEFAULT NULL,
  description VARCHAR NULL DEFAULT NULL,
  category VARCHAR NULL DEFAULT NULL,
  default_price VARCHAR NULL DEFAULT NULL
);